version: 2.1
orbs:
  cypress: cypress-io/cypress@1.7.0
executors:
  with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node14.16.0-chrome90-ff88"
jobs:
  run-app:
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run server
          command: npm start
workflows:
  build:
    jobs:
      - run-app
      - cypress/install
      - cypress/run:
          requires:
            - run-app
            - cypress/install
          executor: with-chrome
          browser: chrome
          post-steps:
            - run: ls
            - store_test_results:
                path: cypress/results
            - store_artifacts:
                path: cypress/screenshots
